---
title: "week3"
author: 
date: 
output: html_document
---

* Practice with [https://www.crowdgrader.org/crowdgrader/venues/view_venue/763](https://www.crowdgrader.org/crowdgrader/venues/view_venue/763)

* Integrating [zotero](www.zotero.com) with [RMarkdown](http://rmarkdown.rstudio.com) will be discussed during the first part of the week.  Example document will be stored in this folder.

* You may find these [videos helpful.](https://www.youtube.com/watch?v=dto4gARbsi0&list=PLJBNI3mCp9g0wsSDK111qgimqVF1dwPXO) 

* Please read pages 13-25 in PDS and take notes as needed.  Read pages 15-57 ISLR.

* Students will continue to work on the citation assignment.


* Watch [Assessing Model Accuracy and Bias-Variance Trade-off video](https://www.youtube.com/watch?v=VusKAosxxyk) (10:04 min)

* Watch [Classification Problems and *K*-Nearest Neighbors video](https://www.youtube.com/watch?v=vVj2itVNku4) (15:37 min)

* Complete Introduction to R Lab section 2.3 ISLR.

* Submit the Literature Review / Citation assignment to [http://www.crowdgrader.org](http://www.crowdgrader.org) no later than 5 pm January 30.  The direct link for this assignment is [http://www.crowdgrader.org/crowdgrader/venues/view_venue/761](http://www.crowdgrader.org/crowdgrader/venues/view_venue/761)

* In the YAML, use the title **Literature Review / Citation Assignment**, and leave the author field blank. 
```
title: "Literature Review / Citation Assignment"
author: 
```
## Grading Rubric

1. Does the document open without problems?  Is the grammar and punctuation acceptable? 0/1

2. How convincing is the written document that further work can be performed on the chosen topic? 0/1

3. Does the author have at least five references? 0/1

A well written paper that convinces you the author has reviewed the literature, has a topic that will expand the knowledge in the area, and has used at least five references should receive a 3.  A submission that satisfies two of the three criteria perfectly or most but not all of the three criteria should receive a 2.  A submission that satisfies only one of the three criteria should receive a 1.  If the submission does not render or the submitter did not submit the correct assignment, they should receive a 0.