---
title: "week2"
author: 
date: 
output: html_document
---

* Read pages 14-28 in PDS, and pages 1-42 in Introduction to Statistical Learning (ISLR)

* Using zotero will be covered the first part of the week.

* This week you will work on your personal Code Book.  You will show the instructor your folder in class on **Thursday, 20 January**.  The instructor will record your folder in the grade book as either a GO or NOGO.  

* This week you will work on the citation assignment from page 18 of PDS.

* Watch [Opening Remarks and Examples video](https://www.youtube.com/watch?v=2wLfFB_6SKI) (18 min)

* Watch [Supervised Learning and Unsupervsed Learning video](https://www.youtube.com/watch?v=LvaTokhYnDw) (12 min)

* Watch [Statistical Learning and Regression video](https://www.youtube.com/watch?v=WjyuiK5taS8) (11:41 min)

* Watch [Curse of Dimensionality and Parametric Models video](https://www.youtube.com/watch?v=UvxHOkYQl8g) (11:40 min)


* [Fork](https://help.github.com/articles/fork-a-repo/) this repository.  

* [Creating RStudio projects from Github Repos (5 min)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) 

* Clone the repository to your local machine using RStudio by following these instructions:
1. Copy the clone URL to the clipboard.
2. Click `File > New Project > Version Control > Git`
3. Paste the clone URL (`https://github.com/YourUserName/STT3851-SP15/STT3851ClassRepoSP15.git`) in the `Repository URL:` box.
4. Type a name (suggestion `UserNameSTT3851`) in the `Project directory name:` box.
5. Change if needed the location in the `Create project as subdirectory of:` box.
6. Click the `Create Project` box.  You should now have a local copy of the forked repository on your local machine.  Congratulations!  

* Set the upstream remote in your fork to this repository with the command
```
git remote add upstream https://github.com/STT3851-SP15/STT3851ClassRepoSP15.git
```
* Verify with
```
git remote -v
```
* To obtain updates from the upstream repository type
```
git pull upstream master
```
* If there are conflicts you will need to resolve them before proceeding.