---
title: "World Development Indicators"
author: "Alan T. Arnholt"
date: "January 31, 2015"
output: html_document
---

```{r comment = NA}
library(WDI)
WDIsearch("CO2")
MOJ <- WDI(country = "all", indicator = c("EN.ATM.CO2E.PC", "EG.USE.COMM.GD.PP.KD"),
    start = 2010, end = 2010, extra = FALSE, cache = NULL)
head(MOJ)
tail(MOJ)
dim(MOJ)
library(dplyr)
library(PDS)
MOJcom <- inner_join(x = gapminder, y = MOJ)
dim(MOJcom)
head(MOJcom)
MOJO <- WDI(country = "all", indicator = c("EN.ATM.CO2E.PC", "EG.USE.COMM.GD.PP.KD"),
    start = 1900, end = 2015, extra = FALSE, cache = NULL)
head(MOJO)
tail(MOJO)
library(ggplot2)
ggplot(data = MOJO, aes(x = year, y = EN.ATM.CO2E.PC, color = country)) + geom_point(alpha = 0.8) + theme_bw() + guides(color = FALSE) + labs(y = "CO2 emissions (metric tons per capita)")
```

```{r comment = NA}
MOJOusa <- subset(MOJO, country == "North America")
ggplot(data = MOJOusa, aes(x = year, y = EN.ATM.CO2E.PC)) + geom_point(alpha = 0.8) + theme_bw() + guides(color = FALSE) + labs(y = "CO2 emissions (metric tons per capita)")
```

```{r comment = NA, warning = FALSE, message = FALSE}
library(dplyr)
MOJOmini <- MOJO %>%
  filter(country == c("China", "United States", "Spain"))
head(MOJOmini)
ggplot(data = MOJOmini, aes(x = year, y = EN.ATM.CO2E.PC, color = country)) + geom_point(alpha = 0.8) + theme_bw() + labs(y = "CO2 emissions (metric tons per capita)")
```