---
title: "week4"
author: 
date: 
output: html_document
---


* Work on **Research Plan Assignment** page 26 PDS.

* Peer reviews for **Citation Assignment** due NLT 5 PM February 6.

* **Research Plan Assignment** see page 26 PDS due NLT 5 PM February 6.  Submit assignment via [http://www.crowdgrader.org](http://www.crowdgrader.org).  The direct link for the assignment is
[http://www.crowdgrader.org/crowdgrader/venues/view_venue/770](http://www.crowdgrader.org/crowdgrader/venues/view_venue/770).

* Read/review pages 18-26 PDS as needed. Read pages 59-82 ISLR.

* Watch [Simple Linear Regression and Confidence Intervals video](https://www.youtube.com/watch?v=PsE9UqoWtS4) (13:01 min)

* Watch [Hypothesis Testing video]( https://www.youtube.com/watch?v=J6AdoiNUyWI) (8:24 min)
 
* Watch [Multiple Linear Regression and Interpreting Regression Coefficients](https://www.youtube.com/watch?v=1hbCJyM9ccs) (15:38 min) 

* Watch [Model Selection and Qualitative Predictors video](https://www.youtube.com/watch?v=3T6RXmIHbJ4) (14:51 min)

## Grading Rubric

1. Does the document open without problems?  Is the grammar and punctuation acceptable? Is the title a concise statement of the main topic?  Does the title identify the actual variables under investigation and the relationship between them? 0/1

2.  Does the introduction describe the question the author intends to investigate and how their research relates to other work in the field?  Does the literature review justify the proposed research by identifying a hole in existing scholarship?  Does the introduction build to and conclude with the research questions or study objectives the author proposes to address?  Is the literature review supported with at least five citations? 0/1

3. Is there a **Methods** section which describes how the research was conducted?  The **Methods** section should include a discussion of the _sample_, _measures_, and _procedures_.  Is there an **Implications/Predicted Results** section that discusses real implications linked to possible results? 0/1

A well written paper that convinces you the author can fill a gap in the existing scholarship, has a title that is a concise statement of the main topic and identifies the actual variables under investigation and the relationship between them, has an introduction supported with at least five references, has a Methods section that describes the sample, measures, and procedures, and has a section that discusses real implications linked to possible results should receive a 3.  A submission that satisfies two of the three criteria perfectly or most but not all of the three criteria should receive a 2.  A submission that satisfies only one of the three criteria should receive a 1.  If the submission does not render or the submitter did not submit the correct assignment, they should receive a 0.
